#image: centos8-php72-ci
stages:
  - test
# phpcpdを実行
phpcpd_job:
  stage: test
  script:
#    - /root/.composer/vendor/bin/phpcpd app
    - ls
# phpmdを実行
phpmd_job:
  stage: test
  script:
#    - /root/.composer/vendor/bin/phpmd app text /root/ruleset.xml
    - ls
# phpunitを実行
phpunit_job:
  stage: test
  script:
#    - /root/.composer/vendor/bin/phpunit tests
    - ls
