export default defineEventHandler(() => ({
    data: [
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
        {
            id: 1,
            title: 'A社 ランディングページ',
            url: 'https://example',
            is_recursive_crawling: true,
            remark: 'memo',
            collect_status: 1,
            collect_schedule_at: '2022/1/1 13:00',
            collect_completed_at: '2022/1/1 15:00',
        },
    ],
    pagination: {
        page: 1,
        limit: 10,
        total: 200,
    },
}));
